[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/sensioai/blog/blob/master/009_algebra_lineal/algebra_lineal.ipynb)

## Objetos matemáticos

### Escalares

In [ ]:
# un valor escalar
x = 1
x

1

### Vectores

In [ ]:
# un vector

import numpy as np

x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [ ]:
# primer valor escalaar

x[0]

1

### Matrices

In [ ]:
# una matriz

A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [ ]:
# primer valor

A[0,0]

1

Utilizaremos matrices para representar imágenes en blanco y negro, los parámetros de una capa en una red neuronal, etc. En la siguiente imágen puedes ver un ejemplo de una imágen con un número 5, como puedes ver se trata de una matriz en la que cada elemento indica la intensidad de color para cada píxel.

![](https://koenig-media.raywenderlich.com/uploads/2018/01/firstXsample.png)

### Tensores

In [ ]:
"""
Podemos ver un `escalar` como un tensor con 0 dimensiones, 
un `vector` como un tensor de 1 dimensión y 
una `matriz` como un tensor de 2 dimensiones. 
"""
# un tensor de 3 dimensiones 
# puedes interpretarlo como dos matrices

A = np.array([[[1, 2], [3, 4]],[[1, 2], [3, 4]]])
A

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

Usaremos tensores de tres dimensiones para representar imágenes en color (canales RGB), tensores de cuatro dimensiones para representar vídeos (secuencia de imágenes en color), etc.

## Operaciones

Una operación importante cuando trabajamos con matrices es la `traspuesta`. Consiste en intercambiar las filas por las columnas, y suele denotarse con el superíndice $(\cdot)^T$, por ejemplo $\mathbf{A}^T$ es la matriz traspuesta de $\mathbf{A}$.

In [ ]:
A = np.arange(10).reshape(2,5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
A.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

Un vector es una matriz de una sola columna, por lo que su transpuesta es simplemente una matriz con una fila con los mismos valores. En cuanto a un valor escalar, él mismo es su traspuesta.

Podemos sumar matrices entre ellas siempre que tengan la misma forma, añadiendo cada elemento de manera independiente.

In [ ]:
A = np.random.randn(3,3)
B = np.random.randn(3,3)

A, B

(array([[-0.44803181,  0.07433018,  2.00647008],
        [ 0.41519541,  0.38976746, -1.02590418],
        [-0.31017224,  0.43283652,  0.50984126]]),
 array([[ 1.08068083, -0.12422565, -0.64136147],
        [ 0.40594424, -0.55789461,  0.01351212],
        [-0.65976357, -0.92149528, -0.60491931]]))

In [ ]:
A + B

array([[ 0.63264902, -0.04989547,  1.36510861],
       [ 0.82113965, -0.16812715, -1.01239207],
       [-0.96993582, -0.48865876, -0.09507806]])

### Multiplicando matrices y vectores

Una de las operaciones más importanes en álgebra lineal es la multiplicación de matrices. Para poder multiplicar dos matrices, $\mathbf{C} = \mathbf{A} \mathbf{B}$, necesitamos que $\mathbf{A}$ tenga el mismo número de columnas que filas tiene $\mathbf{B}$. El resultado, $\mathbf{C}$, será una matriz con el mismo número de filas que $\mathbf{A}$ y el mismo número de columnas que $\mathbf{B}$.

In [ ]:
'''
La práctica de sustituir loops por expresiones basadas en arrays 
se conoce como vectorización, que junto al broadcasting forman la base
de la programación orientada a array (Array-Oriented Programming). 
'''
A = np.array([[1,2,1],[0,1,0],[2,3,4]])
B = np.array([[2,5],[6,7],[1,8]])

A, B

(array([[1, 2, 1],
        [0, 1, 0],
        [2, 3, 4]]), array([[2, 5],
        [6, 7],
        [1, 8]]))

In [ ]:
#Multiplicacion de matices 
C = A.dot(B)
C

array([[15, 27],
       [ 6,  7],
       [26, 63]])

In [ ]:
# notación alternativa

C = A @ B
C

array([[15, 27],
       [ 6,  7],
       [26, 63]])

In [ ]:
C.shape

(3, 2)

Esta operación es distributiva, $\mathbf{A}(\mathbf{B}+\mathbf{C}) = \mathbf{A} \mathbf{B} + \mathbf{A} \mathbf{C}$, y asociativa, $\mathbf{A}(\mathbf{B} \mathbf{C}) = (\mathbf{A} \mathbf{B}) \mathbf{C}$, pero no commutativa, $\mathbf{A} \mathbf{B} \neq \mathbf{B} \mathbf{A}$. Aquí tienes una visualización de la operación.

![](https://thumbs.gfycat.com/PositiveExhaustedAmericangoldfinch-size_restricted.gif)

Ten en cuenta que esta operación no es el resultado de multiplicar cada elemento de las matrices por separado. Este tipo de multiplicación se conoce como `Hardamard product` o `element-wise product` en inglés. En este caso ambas matrices deberán tener la misma forma.

In [ ]:
A = np.random.randn(2,2)
B = np.random.randn(2,2)

A, B

(array([[0.55507675, 0.21085991],
        [0.51566256, 0.23601636]]), array([[-1.48717832, -0.60286189],
        [-0.06992368, -0.79809551]]))

In [ ]:
# multiplicamos cada elemento de manera independiente

A*B

array([[-0.82549811, -0.12711941],
       [-0.03605702, -0.1883636 ]])

## Identidad y matriz inversa

La matriz `identidad` es una matriz con $1$ en todos los valores de su diagonal y $0$ en el resto de valores.

In [1]:
# matriz identidad

I = np.eye(3)
I

NameError: ignored

Esta matriz tiene la propiedad de no alterar ningún vector por el que se multiplique, y nos permite definir la matriz `inversa` como aquella matriz que cumple la condición $\mathbf{A}^{-1} \mathbf{A} = \mathbf{I}$, donde $\mathbf{A}^{-1}$ es la matriz inversa de $\mathbf{A}$ y $\mathbf{I}$ es la matriz identidad. Esta matriz inversa nos permite resolver sistemas de ecuaciones lineales de la forma $\mathbf{A} \mathbf{x} = \mathbf{b}$, donde $\mathbf{A}$ y $\mathbf{b}$ son una matriz y un vector, respectivamente, de valores conocidos y $\mathbf{x}$ es un vector de incógnitas. La solución a este sistema es $\mathbf{x} = \mathbf{A}^{-1} \mathbf{b}$. El problema con la matriz inversa es que no siempre existe y, cuando lo hace, calcularla puede requerir de un tiempo de cálculo considerable, el cual aumenta con el tamaño de $\mathbf{A}$ requiriendo de métodos alternativos de resolución en la gran mayoría de ocasiones.

In [ ]:
import numpy.linalg as linalg

A = np.array([[1,2,3],[5,7,11],[21,29,31]])
A

array([[ 1,  2,  3],
       [ 5,  7, 11],
       [21, 29, 31]])

In [ ]:
#INversa 
linalg.inv(A)

array([[-2.31818182,  0.56818182,  0.02272727],
       [ 1.72727273, -0.72727273,  0.09090909],
       [-0.04545455,  0.29545455, -0.06818182]])

In [ ]:
A  = np.array([[2, 6], [5, 3]])
b = np.array([6, -9])

x = linalg.inv(A).dot(b)
x

array([-3.,  2.])

In [ ]:
# comprobar solución

A.dot(x) == b

array([ True,  True])

## Descomposición de matrices

In [ ]:
A = np.array([[1,2,3],[5,7,11],[21,29,31]])
A

array([[ 1,  2,  3],
       [ 5,  7, 11],
       [21, 29, 31]])

In [ ]:
L, V = linalg.eig(A)
# L -> Valores propios
# V -> Vectores propios
L, V

(array([42.26600592, -0.35798416, -2.90802176]),
 array([[-0.08381182, -0.76283526, -0.18913107],
        [-0.3075286 ,  0.64133975, -0.6853186 ],
        [-0.94784057, -0.08225377,  0.70325518]]))

In [ ]:
# primer vector/valor propio

v, l = V[:,0], L[0]
v, l

(array([-0.08381182, -0.3075286 , -0.94784057]), 42.2660059241356)

No todas las matrices pueden descomponerse de esta manera, pero cuando se puede esta descomposición nos da mucha información sobre la matriz útil para la derivación de propiedades interesantes para el desarrollo de algoritmos (como el signo de los valores propios).

## Otras propiedades

Para terminar vamos a ver algunas otras propiedades interesantes de las matrices que pueden ser útiles. La `diagonal` de una matriz es el vector que contiene todos los elementos de la diagonal de una matriz.

In [ ]:
np.diag(A)

array([ 1,  7, 31])

La `traza` de una matriz es la suma de los elementos de su diagonal.

In [ ]:
np.trace(A)

39

El `determinante` de una matriz es una función que mapea matrices a valores escalares, y su valor absoluto nos da una idea de cuanto se expandirá o contraerá el espacio al multiplicar esa matriz.

In [ ]:
linalg.det(A)

43.99999999999999